### ISSUE TITLE
Error message while using this scrollme.js version

### ISSUE THREAD

**Issue by naBausch** [yarakanigara/scrollme.js#1]
Hello @yarakanigara,

thanks a lot for your version of the scrollme.js Plugin. 
I am getting currently following error message: 
"Uncaught (in promise) TypeError: Failed to execute 'addEventListener' on 'EventTarget': The callback provided as parameter 2 is not a function." (in Chrome and Firefox)
connected to this line of code:
https://github.com/yarakanigara/scrollme.js/blob/master/scrollme.js#L371
which I hope you may can help me with. 

I tried to change _this.init() to  _this.init which would be more correct, but this seems to break the whole plugin. 
Would be great hearing from you! 

Thanks a lot,
Natalie

**Comment by yarakanigara** [comment]
Hi @naBausch 

thank you for your revision, maybe the problem occured on init_events? because in javascript theres no "ready" event, maybe we can fix it with "DOMContentLoaded"? ["DOMContentLoaded", "change", "scroll"] maybe?

Regards,
Yara

**Comment by naBausch** [comment]
Hi @yarakanigara,

thanks for your quick response, I could fix the problem for me by replacing these lines:

```
 // Bind initialisation
    (_this.init_events.join(' ').split(' ')).forEach(function (e) {
        $document.addEventListener(e, _this.init(), false);
    });
```
(https://github.com/yarakanigara/scrollme.js/blob/88f14a2cc045ab82a13394dfbfefe650ff0d0051/scrollme.js#L369)
only with 

`_this.init(); `

The addEventListener expect a function as second parameter, but enter a results, that's the reason for the error. 
Is there any reason why you need the `addEventListener` and why it is necessary to call it `forEach` otherwise I could make a Pull Request :) ? 

Thank you very much and greetings from snowy switzerland :) 

Natalie

**Comment by naBausch** [comment]
Hi @yarakanigara, 
thanks for your input, I tried to fix it in https://github.com/yarakanigara/scrollme.js/pull/2, 
hope this is alright for you :) 

Greetings and have a nice weekend, 

Natalie
